### PR TITLE
Change seed approach again

### LINKED ISSUE #207: Creating objects after seeding the database fails
### Expected behavior
After seeding the database, you should be able to create new objects in the database, as usual.

### Actual behavior
When trying to create a new object (e.g. locker application), you get an error:

```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "locker_applications_pkey"
DETAIL: Key (id)=(1) already exists.
```

### Steps to replicate
From your local codebase:
1. Bring up the servers
```
bundle exec rake servers:start
```
1. Copy the csv files from the staging server 
```
scp deploy@lockers-and-study-spaces-prod1.princeton.edu:\*.csv .
```
1. Run the "seed" task
```
bundle exec rake db:seed
```
1. Bring up the rails server
```
bundle exec rails s
```
1. Go to http://localhost:3000/ and fill out the form and hit submit

### Impact of this bug
We cannot successfully seed the database for development or to reproduce production data on staging

### PR DESCRIPTION
**Pull request by maxkadel**
Closes #207

### CODE REVIEW

File: db/seeds.rb [hunk 1]
```diff
@@ -1,56 +1,222 @@
 # frozen_string_literal: true
 
-require 'csv'
+firestone = Building.find_or_create_by(name: 'Firestone Library', email: 'access@princeton.edu')
+lewis = Building.find_or_create_by(name: 'Lewis Library', email: 'lewislib@princeton.edu')
+Rails.logger.warn("Created #{Building.count} Buildings")
 
-Building.seed
+# Setup flipflop for feature swap - borrowed from https://github.com/voormedia/flipflop/blob/ed1fd56f2f86974004c7af819612dd1622adcf33/lib/tasks/flipflop.rake
+# For some reasone when we use the rake tasks directly, only the first one has an impact
```
Comment (sandbergja) [inline db/seeds.rb:8]: I ran into this recently too.  `#invoke` [only runs if it feels that it is "needed"](https://www.rubydoc.info/gems/rake/Rake%2FTask:invoke)

You can, however, run `#reenable` (and, if needed, `#clear`) like so: https://github.com/pulibrary/lockers_and_study_spaces/blob/8548f8156289ae575d87e31b7dd85c8b914f9325/spec/lib/tasks/lockers_rake_spec.rb#L59-L61

If the rake task doesn't depend on others, I think you can also simply call `#execute` instead of `#invoke`

File: db/seeds.rb [hunk 2]
```diff
@@ -1,56 +1,222 @@
...
-# File was generated using csv:users rake task
-CSV.parse(File.open(Rails.root.join('new_users.csv')), headers: true) do |row|
-  User.find_or_create_by(row.to_hash)
+# Turn Lewis features on
+m.switch_feature!('lewis_staff', 'active_record', true)
+m.switch_feature!('lewis_patrons', 'active_record', true)
+Rails.logger.warn('Turned on Lewis features')
+
+# Lewis features off
+# m.switch_feature!('lewis_staff', 'active_record', false)
```
Comment (sandbergja) [inline db/seeds.rb:18]: I'm not sure we'll remember what this commented-out code does after time passes.  Could we remove it, especially since Lewis is going live soon?

Alternatively, if we want to keep it, could we have it behind some kind of config option (maybe an environment variable)?

File: db/seeds.rb [hunk 3]
```diff
@@ -1,56 +1,222 @@
...
+  user.save
 end
-Rails.logger.warn("Created #{User.count} Users")
 Rails.logger.warn("Created #{User.where(admin: true).count} Administrative Users")
 
-# File was generated using the csv:lockers rake task
-CSV.parse(File.open(Rails.root.join('new_lockers.csv')), headers: true) do |row|
-  Locker.find_or_create_by(row.to_hash)
+# Create regular users
+# Random uids created using Faker::Alphanumeric.unique.alphanumeric(number: 6)
```
Comment (sandbergja) [inline db/seeds.rb:40]: Cool!

File: db/seeds.rb [hunk 4]
```diff
@@ -1,56 +1,222 @@
...
+# For some reasone when we use the rake tasks directly, only the first one has an impact
+m = Object.new
+m.extend Flipflop::Rake::SupportMethods
 
-# File was generated using csv:users rake task
-CSV.parse(File.open(Rails.root.join('new_users.csv')), headers: true) do |row|
-  User.find_or_create_by(row.to_hash)
+# Turn Lewis features on
+m.switch_feature!('lewis_staff', 'active_record', true)
+m.switch_feature!('lewis_patrons', 'active_record', true)
```
Comment (sandbergja) [inline db/seeds.rb:14]: This worked for me locally without the `Flipflop::Rake::SupportMethods` workaround:
```suggestion
Rake::Task['flipflop:turn_on'].execute(feature: 'lewis_staff', strategy: 'active_record')
Rake::Task['flipflop:turn_on'].execute(feature: 'lewis_patrons', strategy: 'active_record')
```

**Review by sandbergja — CHANGES_REQUESTED** [review]
Thanks, @maxkadel !  `rake db:seed:replant` worked well for me -- and the new seeding strategy is so fast!

I'd advocate for removing the commented out routines.  It might be nice to call the FlipFlop Rake tasks themselves, rather than the workaround approach, but I don't feel as strongly about that.

File: db/seeds.rb (hunk 1 above)
Comment (maxkadel) [reply db/seeds.rb:8]: Ah, good info to have! Thank you!

**Review by sandbergja — APPROVED** [review]
🎉🎉🎉 thanks, @maxkadel !
